-- Profile fields collected at registration (mirrors legacy user document shape).

alter table public.profiles
  add column if not exists display_name text,
  add column if not exists name text,
  add column if not exists surname text,
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists city text,
  add column if not exists age integer default 18,
  add column if not exists position text,
  add column if not exists experience text,
  add column if not exists avatar_url text,
  add column if not exists rating double precision default 3.0,
  add column if not exists match_rating double precision default 3.0,
  add column if not exists video_rating double precision default 3.0,
  add column if not exists total_matches integer default 0,
  add column if not exists total_videos integer default 0,
  add column if not exists rating_history jsonb default '[]'::jsonb,
  add column if not exists coins integer default 160,
  add column if not exists matches integer default 0,
  add column if not exists goals integer default 0,
  add column if not exists assists integer default 0,
  add column if not exists subscription text default 'champions_league',
  add column if not exists subscription_expiry timestamptz,
  add column if not exists subscription_active boolean default true,
  add column if not exists challenges_created integer default 0,
  add column if not exists max_challenges_per_month integer default 999;
